name: 'AWS CDK Plan Auditor'
description: 'Mange and review you CDK diff outputs in GitHub pull requests.'
author: 'Dave Dennis'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'info'
  color: 'purple'

# Define your inputs here.
inputs:
  repo-token:
    description: 'Action CI Automatic Repo Token.'
    required: true

# Define your outputs here.
outputs:
  cdkOutPutPath:
    description: 'Your cdk.log output file destination'

runs:
  using: node20
  main: dist/index.js