name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  repo-token:
    description: 'Action CI Automatic Repo Token.'
    required: true

# Define your outputs here.
outputs:
  cdkOutPutPath:
    description: 'Your cdk.log output file destination'

runs:
  using: node20
  main: dist/index.js